### ISSUE TITLE
Close and OK buttons do not show on Gnome3

### ISSUE THREAD

**Issue by pcav** [msweier/QGIS-Drainage-Channel-Builder#3]
Please see other plugins, or ask on the mailing list (a rather common problem).

**Comment by msweier** [comment]
Seems like another Gnome3 did not experience the problem.
http://lists.osgeo.org/pipermail/qgis-developer/2015-January/036535.html
I did set the text of the "Ok" button to "Run 2D" and the "Cancel" button should have the same functionality as "Close".  Is it an issue where the window needs to be resized to see them?

**Comment by pcav** [comment]
See the attached. If one opens the dialog, he does not have a button to close it without running the analysis.
A minor issue, as one could close it right-clicking on the top bar; however, it is nice to show a predictable interface to the casual user.

**Comment by msweier** [comment]
Hmm, I didn't get the screenshot.  Can you try and repost?  You should be able to get out of the program at anytime by clicking on the "Cancel" button.  I agree the UI should work predictablly.

**Comment by pcav** [comment]
![drain_gnome3](https://cloud.githubusercontent.com/assets/691842/5960573/c6c0e89e-a7d6-11e4-8668-5de6b72f4db8.png)

Oh, I see. The user expects the OK and Close buttons right at the end of the dialog, so I would suggest to move it there.
Another minor issue, sorry if I'm bothering.

**Comment by msweier** [comment]
Not at all...I appreciate the feedback...I haven't done much GUI work so it's a learning process.  I will move them to the bottom.
