### ISSUE TITLE
Please clarify what type of input

### ISSUE THREAD

**Issue by pcav** [msweier/QGIS-Drainage-Channel-Builder#4]
A single line is not accepted, please provide a hint.

**Comment by msweier** [comment]
A single line vector layer is what is required for the channel centerline....is it possible to send the DEM and vector line you used for testing?

**Comment by msweier** [comment]
I will clarify in the documentation that mutlistring geometries (which are typical of hydrography layers) are not supported.  The reason this is not supported by automatically merging them is there is no way of telling which direction each part was drawn.
