### ISSUE TITLE
Please add color ramp

### ISSUE THREAD

**Issue by pcav** [msweier/QGIS-Drainage-Channel-Builder#6]
A nice, suitable color ramp is applied automatically to ChannelDepth, whereas it is not to ChannelElev, so one has to fix it by hand.
Please apply a different one also to the second.

**Comment by msweier** [comment]
The ChannelElev layer adopts the layer style assigned to the input DEM.  Creates the appearance of the ChannelElev layer seamlessly merging into the input DEM.

![screen shot 2015-01-29 at 9 20 36 am](https://cloud.githubusercontent.com/assets/9432394/5960018/2e85a4c2-a798-11e4-9b94-7e6d54cd9dc0.png)
![screen shot 2015-01-29 at 9 20 43 am](https://cloud.githubusercontent.com/assets/9432394/5960022/327d55b6-a798-11e4-82a0-de0cf9dd13b3.png)
![screen shot 2015-01-29 at 9 20 49 am](https://cloud.githubusercontent.com/assets/9432394/5960024/34fc1ec6-a798-11e4-9429-3972823bab8b.png)

**Comment by pcav** [comment]
I understand, but the result has much less dynamic, so for a grayscale input you'll end up having a grey block, not very attractive, nor particularly understandable.
Cosmetic stuff, however.
