### ISSUE TITLE
Please update README

### ISSUE THREAD

**Issue by saberraz** [msweier/QGIS-Drainage-Channel-Builder#8]
It is not clear from the README file what the plugin is supposed to do? Could you add some notes?
Cheers,
Saber

**Comment by msweier** [comment]
Agreed, working on it.

**Comment by saberraz** [comment]
Thanks...hopefully I can contribute.

**Comment by msweier** [comment]
Sure any contributions are welcome...although I must admit I would structure my code differently if I were to do a rewrite!
